version: '3.4'

services:
  db:
    container_name: "api_db"
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
